# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SDL3_mixer::SDL3_mixer-shared SDL3_mixer::ogg SDL3_mixer::opus SDL3_mixer::opusfile SDL3_mixer::gme SDL3_mixer::xmp_shared SDL3_mixer::WavPack)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SDL3_mixer::SDL3_mixer-shared
add_library(SDL3_mixer::SDL3_mixer-shared SHARED IMPORTED)

set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  COMPATIBLE_INTERFACE_BOOL "SDL3_SHARED"
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/include"
  INTERFACE_LINK_LIBRARIES "SDL3::Headers"
  INTERFACE_SDL3_SHARED "ON"
)

# Create imported target SDL3_mixer::ogg
add_library(SDL3_mixer::ogg SHARED IMPORTED)

set_target_properties(SDL3_mixer::ogg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/include;D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/include"
)

# Create imported target SDL3_mixer::opus
add_library(SDL3_mixer::opus SHARED IMPORTED)

set_target_properties(SDL3_mixer::opus PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/include"
)

# Create imported target SDL3_mixer::opusfile
add_library(SDL3_mixer::opusfile SHARED IMPORTED)

set_target_properties(SDL3_mixer::opusfile PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/include"
  INTERFACE_LINK_LIBRARIES "SDL3_mixer::ogg;SDL3_mixer::opus;\$<\$<BOOL:>:m>"
)

# Create imported target SDL3_mixer::gme
add_library(SDL3_mixer::gme SHARED IMPORTED)

set_target_properties(SDL3_mixer::gme PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/.."
)

# Create imported target SDL3_mixer::xmp_shared
add_library(SDL3_mixer::xmp_shared SHARED IMPORTED)

set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/include"
)

# Create imported target SDL3_mixer::WavPack
add_library(SDL3_mixer::WavPack SHARED IMPORTED)

set_target_properties(SDL3_mixer::WavPack PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/include"
)

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/RelWithDebInfo/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/RelWithDebInfo/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/RelWithDebInfo/ogg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/RelWithDebInfo/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/RelWithDebInfo/opus.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/RelWithDebInfo/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/RelWithDebInfo/opusfile.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/RelWithDebInfo/opusfile-0.dll"
  )

# Import target "SDL3_mixer::gme" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::gme APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::gme PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/RelWithDebInfo/gme.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/RelWithDebInfo/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/RelWithDebInfo/libxmp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/RelWithDebInfo/libxmp.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/RelWithDebInfo/libwavpack.dll.a"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/RelWithDebInfo/libwavpack-1.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "Debug"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/Debug/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "SDL3::SDL3-shared"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/Debug/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "Debug"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/Debug/ogg.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/Debug/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "Debug"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/Debug/opus.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/Debug/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "Debug"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/Debug/opusfile.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/Debug/opusfile-0.dll"
  )

# Import target "SDL3_mixer::gme" for configuration "Debug"
set_property(TARGET SDL3_mixer::gme APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::gme PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/Debug/gme.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/Debug/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "Debug"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/Debug/libxmp.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/Debug/libxmp.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "Debug"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/Debug/libwavpack.dll.a"
  IMPORTED_LOCATION_DEBUG "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/Debug/libwavpack-1.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "Release"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/Release/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/Release/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "Release"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/Release/ogg.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/Release/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "Release"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/Release/opus.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/Release/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "Release"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/Release/opusfile.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/Release/opusfile-0.dll"
  )

# Import target "SDL3_mixer::gme" for configuration "Release"
set_property(TARGET SDL3_mixer::gme APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::gme PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/Release/gme.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/Release/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "Release"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/Release/libxmp.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/Release/libxmp.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "Release"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/Release/libwavpack.dll.a"
  IMPORTED_LOCATION_RELEASE "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/Release/libwavpack-1.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/MinSizeRel/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "SDL3::SDL3-shared"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/MinSizeRel/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/MinSizeRel/ogg.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/ogg/MinSizeRel/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/MinSizeRel/opus.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opus/MinSizeRel/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/MinSizeRel/opusfile.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/opusfile/MinSizeRel/opusfile-0.dll"
  )

# Import target "SDL3_mixer::gme" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::gme APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::gme PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/MinSizeRel/gme.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libgme/gme/MinSizeRel/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/MinSizeRel/libxmp.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/libxmp/MinSizeRel/libxmp.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/MinSizeRel/libwavpack.dll.a"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/Code/cpp/Repositories/dm-cmake/SDL_mixer-build/external/wavpack/MinSizeRel/libwavpack-1.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
